[package]
name = "terminal-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
iced = { version = "=0.14.0", default-features = false, features = ["advanced", "tokio", "wgpu", "x11"] }
shell-words = "=1.1.1"
ui-lang-components = { path = "../../crates/ui-lang-components", default-features = false, features = ["terminal"] }
ui-lang.workspace = true
ui-lang-runtime.workspace = true
which = "=8.0.6"

[build-dependencies]
ui-lang-build.workspace = true

[lints]
workspace = true

[dev-dependencies]
ui-lang-runtime = { workspace = true, features = ["test-runtime"] }
