//! From a seed phrase to the one key an account owner actually holds.
//!
//! Every other key in this app is one it made for itself: an agent wallet, an
//! API key, both disposable and both approved by something else. This module
//! is the something else — the account's own key, the one that authorises an
//! enrolment and the one whose loss is not recoverable. It is the most
//! dangerous code in the tree, and it is written to be checkable rather than
//! clever.
//!
//! ## What is implemented, and against what
//!
//! BIP-39 (phrase to seed) and BIP-32 (seed to key along a path), hand-written
//! on `hmac`, `sha2` and `k256`, which were already in the lockfile. The house
//! rule for anything cryptographic applies and is the whole reason this is
//! acceptable to hand-write: **nothing here is checked against itself.**
//!
//! * BIP-39 against the Trezor vectors — the reference implementation's own —
//!   at all three entropy sizes, with and without a passphrase.
//! * BIP-32 against the spec's published test vectors, over a chain that mixes
//!   hardened and normal derivation.
//! * The whole path, phrase to Ethereum address, against pairs generated by a
//!   real **ethers.js v6.17.0** run. How they were made is recorded beside them
//!   so anyone can make them again.
//!
//! The two oracles cross-check: ethers' seed for `abandon…about` under the
//! passphrase `TREZOR` is byte-for-byte the Trezor vector's, which is a thing
//! neither project copied from the other.
//!
//! ## What is deliberately refused
//!
//! * **A non-ASCII passphrase.** BIP-39 says to NFKD-normalise the phrase and
//!   the passphrase before stretching them. For English words and an ASCII
//!   passphrase that is the identity, so this implements it by *refusing*
//!   anything else rather than by pulling in a Unicode normalisation table to
//!   be right about a case the app can decline. A passphrase this cannot
//!   normalise is a different seed silently, which is the one failure a seed
//!   phrase must never have.
//! * **A phrase whose checksum does not hold.** A mistyped word usually breaks
//!   it, and a broken checksum is caught here rather than discovered as an
//!   account that is empty for no visible reason.
//!
//! ## What is not defended against
//!
//! The bytes live in this process while a phrase is being imported, and Rust
//! cannot promise where the optimiser put a copy. Every buffer this module
//! *names* is wiped; see `Drop` on `PrivateKey` in `lighter_sign.rs` for the
//! same statement made at greater length. The mitigation that actually holds is
//! upstream of this file: the phrase is asked for once, converted, and handed
//! to the platform keychain, and the app never asks for it again.

// Complete and held to its oracles, and pointed at by nothing until the
// custody panel can take a phrase — the shape `signing.rs`, `lighter_sign.rs`
// and the order path each landed in first. Built and proven before a field can
// reach it, rather than arriving in the same change as the field that spends
// somebody's account.
#![allow(dead_code)]

use hmac::{Hmac, Mac};
use sha2::{Digest, Sha256, Sha512};

use crate::hyperliquid::HlError;

/// The official BIP-39 English wordlist, verbatim.
///
/// Data rather than code, and checked as data: `the_wordlist_is_the_official_one`
/// hashes it. A single corrupted word would not fail to compile, would not fail
/// to parse, and would derive a wrong account for exactly the phrases that
/// contain it — so the file is pinned by digest and not by eye.
const WORDLIST: &str = include_str!("bip39-english.txt");

/// PBKDF2's round count for BIP-39. Not a tuning knob: the spec says 2048 and a
/// different number is a different seed.
const STRETCH_ROUNDS: u32 = 2_048;

/// What a phrase can be wrong in.
///
/// Never carries the phrase, or any part of it, for the reason `SignError`
/// never carries a key: a message about a secret has a way of reaching a log.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum SeedError {
    /// Not 12, 15, 18, 21 or 24 words.
    WordCount,
    /// A word that is not in the list. Named as a position so a reader can find
    /// it without the message quoting it.
    UnknownWord(usize),
    /// The words are all real and their checksum does not hold, which is what a
    /// mistyped or transposed word usually looks like.
    Checksum,
    /// A passphrase this module will not normalise. See the header.
    Passphrase,
    /// The path reached a child that is not a usable key. Astronomically
    /// unlikely and not ignorable: the spec says to skip to the next index, and
    /// pretending it cannot happen is how a wrong key gets derived.
    Derivation,
}

impl SeedError {
    /// What the panel says. The phrase never appears in it.
    pub fn message(self) -> String {
        match self {
            SeedError::WordCount => "A recovery phrase is 12, 15, 18, 21 or 24 words.".to_owned(),
            SeedError::UnknownWord(at) => {
                format!("Word {} is not a recovery-phrase word.", at + 1)
            }
            SeedError::Checksum => "That phrase does not check out — a word is wrong or two are \
                                    swapped. Nothing was stored."
                .to_owned(),
            SeedError::Passphrase => "The passphrase has to be plain ASCII here.".to_owned(),
            SeedError::Derivation => {
                "That phrase does not derive a usable key on this path.".to_owned()
            }
        }
    }
}

impl From<SeedError> for HlError {
    fn from(error: SeedError) -> Self {
        HlError::new(error.message())
    }
}

/// The 64-byte seed a phrase stretches into.
///
/// Wrapped rather than a bare array so it cannot be printed, cloned about, or
/// passed where a public value is expected. It is wiped on the way out.
pub struct Seed([u8; 64]);

impl Drop for Seed {
    fn drop(&mut self) {
        self.0.fill(0);
        std::hint::black_box(&mut self.0);
    }
}

impl std::fmt::Debug for Seed {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str("Seed(<redacted>)")
    }
}

impl Seed {
    /// The bytes, for the one caller that derives from them.
    fn bytes(&self) -> &[u8; 64] {
        &self.0
    }
}

/// Stretch a recovery phrase into its seed.
///
/// The phrase is validated first — every word in the list, and the checksum the
/// last word carries — so a mistyped phrase is refused here rather than
/// silently deriving somebody else's empty account.
///
/// Whitespace is forgiving because a phrase gets pasted: any run of spaces,
/// tabs or newlines separates words, and the case is folded, because a wallet
/// that printed the phrase in capitals wrote the same phrase.
pub fn seed_from_phrase(phrase: &str, passphrase: &str) -> Result<Seed, SeedError> {
    if !passphrase.is_ascii() {
        return Err(SeedError::Passphrase);
    }
    let words: Vec<String> = phrase
        .split_whitespace()
        .map(|word| word.to_lowercase())
        .collect();
    check_phrase(&words)?;

    // The spec stretches the phrase in its canonical spelling — single spaces,
    // lower case — rather than however it was typed.
    let mut canonical = words.join(" ").into_bytes();
    let mut salt = format!("mnemonic{passphrase}").into_bytes();
    let seed = Seed(stretch(&canonical, &salt));
    canonical.fill(0);
    salt.fill(0);
    std::hint::black_box((&mut canonical, &mut salt));
    Ok(seed)
}

/// Every word in the list, and the checksum the phrase carries.
///
/// The checksum is what a wordlist alone cannot give: eleven bits per word, of
/// which the last few are a hash of the rest, so a single wrong word fails with
/// probability about 1 - 2^-4 at twelve words and better at longer ones. It is
/// the difference between "this is a phrase" and "this is *the* phrase".
fn check_phrase(words: &[String]) -> Result<(), SeedError> {
    if !matches!(words.len(), 12 | 15 | 18 | 21 | 24) {
        return Err(SeedError::WordCount);
    }
    let mut bits: Vec<bool> = Vec::with_capacity(words.len() * 11);
    for (at, word) in words.iter().enumerate() {
        let index = index_of(word).ok_or(SeedError::UnknownWord(at))?;
        for shift in (0..11).rev() {
            bits.push(index >> shift & 1 == 1);
        }
    }
    // The last len/32 bits are the checksum; everything before them is the
    // entropy the phrase encodes.
    let checksum_bits = bits.len() / 33;
    let entropy_bits = bits.len() - checksum_bits;
    let mut entropy = vec![0u8; entropy_bits / 8];
    for (at, bit) in bits[..entropy_bits].iter().enumerate() {
        if *bit {
            entropy[at / 8] |= 1 << (7 - at % 8);
        }
    }
    let digest = Sha256::digest(&entropy);
    let held = bits[entropy_bits..]
        .iter()
        .enumerate()
        .all(|(at, bit)| (digest[at / 8] >> (7 - at % 8) & 1 == 1) == *bit);
    entropy.fill(0);
    std::hint::black_box(&mut entropy);
    held.then_some(()).ok_or(SeedError::Checksum)
}

/// A word's position in the list, or nothing.
///
/// Linear over 2048 short strings, once per word, on a path a person reaches by
/// typing a phrase.
///
/// ponytail: a map would turn 2048 comparisons into one hash and is not worth
/// the static; if this ever runs anywhere but an import, build one.
fn index_of(word: &str) -> Option<u16> {
    WORDLIST
        .lines()
        .position(|listed| listed == word)
        .map(|at| at as u16)
}

/// PBKDF2-HMAC-SHA512, only as much of it as one 64-byte block needs.
///
/// Written out because that is twelve lines over the HMAC already in the tree,
/// against a dependency whose whole job is those twelve lines. The single block
/// is not a shortcut: the output is exactly one SHA-512 wide, so the block loop
/// a general implementation carries would run once.
fn stretch(password: &[u8], salt: &[u8]) -> [u8; 64] {
    let mut salted = salt.to_vec();
    // Block index 1, big-endian, which is the whole of PBKDF2's block counter
    // for an output this size.
    salted.extend_from_slice(&1u32.to_be_bytes());
    let mut current = hmac_sha512(password, &salted);
    let mut out = current;
    for _ in 1..STRETCH_ROUNDS {
        current = hmac_sha512(password, &current);
        for (byte, mixed) in out.iter_mut().zip(current) {
            *byte ^= mixed;
        }
    }
    salted.fill(0);
    current.fill(0);
    std::hint::black_box((&mut salted, &mut current));
    out
}

fn hmac_sha512(key: &[u8], message: &[u8]) -> [u8; 64] {
    let mut mac =
        <Hmac<Sha512> as Mac>::new_from_slice(key).expect("HMAC takes a key of any length");
    mac.update(message);
    mac.finalize().into_bytes().into()
}

/// Where an Ethereum account lives under a seed.
///
/// Not a setting. Every wallet an owner is likely to hold this phrase in —
/// MetaMask, Rabby, anything ethers builds — puts the first account here, so a
/// second path would be a way to derive an address the owner has never seen
/// while every screen still looked right. `defaultPath` in ethers' own
/// `hdwallet.ts` is this string.
const ETHEREUM_PATH: [u32; 5] = [44 | HARDENED, 60 | HARDENED, HARDENED, 0, 0];

/// BIP-32's hardened marker: the top bit of the index.
const HARDENED: u32 = 0x8000_0000;

/// Derive the account key at `m/44'/60'/0'/0/0`.
///
/// The 32 bytes it answers are a secp256k1 private key, and every use of them
/// in this app goes through `signing::MasterKey`, which will sign an enrolment
/// and nothing else.
pub fn ethereum_key(seed: &Seed) -> Result<[u8; 32], SeedError> {
    // The master key is an HMAC of the seed under a fixed string, which is what
    // makes a BIP-32 tree deterministic from the phrase alone.
    let mut wide = hmac_sha512(b"Bitcoin seed", seed.bytes());
    let mut key: [u8; 32] = wide[..32].try_into().expect("32 bytes");
    let mut chain: [u8; 32] = wide[32..].try_into().expect("32 bytes");
    for index in ETHEREUM_PATH {
        (key, chain) = child(&key, &chain, index)?;
    }
    wide.fill(0);
    chain.fill(0);
    std::hint::black_box((&mut wide, &mut chain));
    Ok(key)
}

/// One step down the tree.
///
/// The two cases differ in what goes into the HMAC and nothing else: a hardened
/// child commits to the *private* key, so knowing the parent's public key and
/// chain code is not enough to derive it; a normal child commits to the public
/// key, which is what lets a watch-only wallet walk the same branch. The path
/// above is hardened where the spec says an account should be.
fn child(key: &[u8; 32], chain: &[u8; 32], index: u32) -> Result<([u8; 32], [u8; 32]), SeedError> {
    let parent = k256::SecretKey::from_slice(key).map_err(|_| SeedError::Derivation)?;
    let mut message = Vec::with_capacity(37);
    if index & HARDENED == 0 {
        message.extend_from_slice(parent.public_key().to_sec1_bytes().as_ref());
    } else {
        message.push(0);
        message.extend_from_slice(key);
    }
    message.extend_from_slice(&index.to_be_bytes());

    let mut wide = hmac_sha512(chain, &message);
    let offset = k256::SecretKey::from_slice(&wide[..32]).map_err(|_| SeedError::Derivation)?;
    // The child key is the parent plus the HMAC's left half, in the scalar
    // field — and a sum that lands on zero is the one case the spec says to
    // refuse rather than use.
    let sum = *offset.to_nonzero_scalar().as_ref() + parent.to_nonzero_scalar().as_ref();
    let child = k256::SecretKey::new(sum.into())
        .to_bytes()
        .as_slice()
        .try_into()
        .map_err(|_| SeedError::Derivation)?;
    let chain: [u8; 32] = wide[32..].try_into().expect("32 bytes");

    message.fill(0);
    wide.fill(0);
    std::hint::black_box((&mut message, &mut wide));
    Ok((child, chain))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::signing::Wallet;

    /// The phrase every BIP-39 implementation tests against, at the entropy
    /// size it is usually written at.
    const ZEROS: &str = "abandon abandon abandon abandon abandon abandon abandon abandon abandon \
                         abandon abandon about";

    fn hex(bytes: &[u8]) -> String {
        bytes.iter().map(|byte| format!("{byte:02x}")).collect()
    }

    fn seed(phrase: &str, passphrase: &str) -> Seed {
        seed_from_phrase(phrase, passphrase).expect("a phrase from the vectors")
    }

    /// The wordlist is data, so it is checked as data.
    ///
    /// A single corrupted word compiles, parses, and derives a wrong account
    /// for exactly the phrases containing it — an owner would see an empty
    /// account and no reason for it. The digest is the official list's, which
    /// is published and widely quoted.
    #[test]
    fn the_wordlist_is_the_official_one() {
        assert_eq!(
            hex(&Sha256::digest(WORDLIST.as_bytes())),
            "2f5eed53a4727b4bf8880d8f3f199efc90e58503646d9ff8eff3a2ed3b24dbda",
        );
        let words: Vec<&str> = WORDLIST.lines().collect();
        assert_eq!(words.len(), 2_048, "eleven bits per word, exactly");
        assert_eq!((words[0], words[2_047]), ("abandon", "zoo"));
        // Sorted, which is what makes the list searchable and is a property of
        // the official one rather than of any list of 2048 words.
        assert!(words.windows(2).all(|pair| pair[0] < pair[1]));
    }

    /// BIP-39, against the reference implementation's own vectors.
    ///
    /// `trezor/python-mnemonic`'s `vectors.json`, which is where every
    /// implementation of this checks itself. All three entropy sizes, because
    /// the checksum length changes with them and a bug in the bit packing shows
    /// up at one size and not another. Every one of these carries the
    /// passphrase `TREZOR`, which is the vectors' own.
    #[test]
    fn a_phrase_stretches_to_the_seed_the_reference_implementation_makes() {
        for (phrase, expected) in [
            (
                ZEROS,
                "c55257c360c07c72029aebc1b53c05ed0362ada38ead3e3e9efa3708e534955\
                 31f09a6987599d18264c1e1c92f2cf141630c7a3c4ab7c81b2f001698e7463b04",
            ),
            (
                "letter advice cage absurd amount doctor acoustic avoid letter advice cage \
                 absurd amount doctor acoustic avoid letter always",
                "107d7c02a5aa6f38c58083ff74f04c607c2d2c0ecc55501dadd72d025b751bc2\
                 7fe913ffb796f841c49b1d33b610cf0e91d3aa239027f5e99fe4ce9e5088cd65",
            ),
            (
                "legal winner thank year wave sausage worth useful legal winner thank year wave \
                 sausage worth useful legal winner thank year wave sausage worth title",
                "bc09fca1804f7e69da93c2f2028eb238c227f2e9dda30cd63699232578480a40\
                 21b146ad717fbb7e451ce9eb835f43620bf5c514db0f8add49f5d121449d3e87",
            ),
        ] {
            assert_eq!(
                hex(seed(phrase, "TREZOR").bytes()),
                expected.replace(['\n', ' '], ""),
                "{} words",
                phrase.split_whitespace().count(),
            );
        }
    }

    /// A passphrase is part of the seed, and no passphrase is a passphrase too.
    ///
    /// The pair matters more than either half: the same twelve words under two
    /// passphrases are two unrelated accounts, so an owner who uses one and is
    /// not asked for it would be shown an empty account belonging to nobody.
    /// The app asks, and shows the address it derived before storing anything.
    ///
    /// Both figures come from a real ethers.js v6.17.0 run — see the header for
    /// how — and the second is also the Trezor vector above, which is the two
    /// oracles agreeing without either having copied the other.
    #[test]
    fn a_passphrase_makes_a_different_account_of_the_same_words() {
        assert_eq!(
            hex(seed(ZEROS, "").bytes()),
            "5eb00bbddcf069084889a8ab9155568165f5c453ccb85e70811aaed6f6da5fc1\
             9a5ac40b389cd370d086206dec8aa6c43daea6690f20ad3d8d48b2d2ce9e38e4"
                .replace(['\n', ' '], ""),
        );
        assert_ne!(
            hex(seed(ZEROS, "").bytes()),
            hex(seed(ZEROS, "TREZOR").bytes()),
            "a passphrase that changed nothing would be a passphrase nobody's \
             account depends on",
        );
    }

    /// BIP-32, against the spec's own Test Vector 1.
    ///
    /// The chain is the spec's and is chosen for what it mixes: hardened and
    /// normal children, and an index past 2^31 that a signed shift would get
    /// wrong. The bytes are what `ethers` derives, and the run that produced
    /// them also checked its extended keys against the spec's published `xprv`
    /// strings at every node — so these are the spec's numbers, reached through
    /// an implementation that proves it reproduces them.
    #[test]
    fn the_spec_s_own_derivation_chain() {
        let mut wide = hmac_sha512(
            b"Bitcoin seed",
            &hex_bytes("000102030405060708090a0b0c0d0e0f"),
        );
        let mut key: [u8; 32] = wide[..32].try_into().expect("32 bytes");
        let mut chain: [u8; 32] = wide[32..].try_into().expect("32 bytes");
        assert_eq!(
            (hex(&key), hex(&chain)),
            (
                "e8f32e723decf4051aefac8e2c93c9c5b214313817cdb01a1494b917c8436b35".to_owned(),
                "873dff81c02f525623fd1fe5167eac3a55a049de3d314bb42ee227ffed37d508".to_owned(),
            ),
            "m",
        );

        for (index, expected_key, expected_chain) in [
            (
                HARDENED,
                "edb2e14f9ee77d26dd93b4ecede8d16ed408ce149b6cd80b0715a2d911a0afea",
                "47fdacbd0f1097043b78c63c20c34ef4ed9a111d980047ad16282c7ae6236141",
            ),
            (
                1,
                "3c6cb8d0f6a264c91ea8b5030fadaa8e538b020f0a387421a12de9319dc93368",
                "2a7857631386ba23dacac34180dd1983734e444fdbf774041578e9b6adb37c19",
            ),
            (
                2 | HARDENED,
                "cbce0d719ecf7431d88e6a89fa1483e02e35092af60c042b1df2ff59fa424dca",
                "04466b9cc8e161e966409ca52986c584f07e9dc81f735db683c3ff6ec7b1503f",
            ),
            (
                2,
                "0f479245fb19a38a1954c5c7c0ebab2f9bdfd96a17563ef28a6a4b1a2a764ef4",
                "cfb71883f01676f587d023cc53a35bc7f88f724b1f8c2892ac1275ac822a3edd",
            ),
            (
                1_000_000_000,
                "471b76e389e528d6de6d816857e012c5455051cad6660850e58372a6c3e6e7c8",
                "c783e67b921d2beb8f6b389cc646d7263b4145701dadd2161548a8b078e65e9e",
            ),
        ] {
            (key, chain) = child(&key, &chain, index).expect("a derivable child");
            assert_eq!(
                (hex(&key), hex(&chain)),
                (expected_key.to_owned(), expected_chain.to_owned())
            );
        }
        wide.fill(0);
    }

    /// The whole road: a phrase, to the address a wallet would show for it.
    ///
    /// This is the claim an owner checks with their own eyes on the panel, so
    /// it is the one held against a real run of the thing they use. Generated
    /// with **ethers.js v6.17.0**, `HDNodeWallet.fromMnemonic(m,
    /// "m/44'/60'/0'/0/0").address`, over four phrases: the canonical one, a
    /// second twelve-word phrase, the canonical one under a passphrase, and a
    /// twenty-four-word phrase.
    ///
    /// The address is computed by this app's own `Wallet`, whose derivation is
    /// separately pinned against Foundry — so a pass here is the phrase, the
    /// path *and* the address agreeing with two outside implementations.
    #[test]
    fn a_phrase_derives_the_address_a_wallet_shows() {
        for (phrase, passphrase, expected) in [
            (ZEROS, "", "0x9858effd232b4033e47d90003d41ec34ecaeda94"),
            (
                "legal winner thank year wave sausage worth useful legal winner thank yellow",
                "",
                "0x58a57ed9d8d624cbd12e2c467d34787555bb1b25",
            ),
            (
                ZEROS,
                "TREZOR",
                "0x9c32f71d4db8fb9e1a58b0a80df79935e7256fa6",
            ),
            (
                "zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo zoo \
                 zoo zoo zoo vote",
                "",
                "0x1959f5f4979c5cd87d5cb75c678c770515cb5e0e",
            ),
        ] {
            let key = ethereum_key(&seed(phrase, passphrase)).expect("a derivable account");
            let wallet = Wallet::from_secret(&key).expect("a usable secp256k1 key");
            assert_eq!(
                wallet.address().to_string(),
                expected,
                "{} words, passphrase {:?}",
                phrase.split_whitespace().count(),
                passphrase,
            );
        }
    }

    /// However it was typed, it is the same phrase. Wallets print them in
    /// columns, in capitals, and with the line breaks of whatever printed them.
    #[test]
    fn a_phrase_survives_however_it_was_pasted() {
        let canonical = hex(seed(ZEROS, "").bytes());
        for spelling in [
            "ABANDON ABANDON ABANDON ABANDON ABANDON ABANDON ABANDON ABANDON ABANDON ABANDON \
             ABANDON ABOUT",
            "  abandon   abandon abandon\tabandon abandon abandon\nabandon abandon abandon \
             abandon abandon about  ",
        ] {
            assert_eq!(hex(seed(spelling, "").bytes()), canonical);
        }
    }

    /// A phrase that is wrong is refused, rather than deriving somebody's empty
    /// account.
    ///
    /// The checksum is what makes this possible at all: a wordlist alone says a
    /// phrase is *made of words*, and the last word's bits say it is *this*
    /// phrase. Without the check, one wrong word is an account the owner has
    /// never seen, with nothing on screen to say so.
    #[test]
    fn a_mistyped_phrase_is_refused_rather_than_derived() {
        // One word swapped for another real word: every word is in the list, and
        // the checksum is not.
        let swapped = ZEROS.replacen("abandon", "ability", 1);
        assert_eq!(
            seed_from_phrase(&swapped, "").unwrap_err(),
            SeedError::Checksum
        );
        // Two real words transposed, which is the other way a careful person
        // gets it wrong.
        assert_eq!(
            seed_from_phrase(
                "legal winner thank year wave sausage worth useful legal winner yellow thank",
                ""
            )
            .unwrap_err(),
            SeedError::Checksum,
        );
        // A word that is not a word, named by position so the message can point
        // at it without quoting the phrase.
        assert_eq!(
            seed_from_phrase(&ZEROS.replacen("abandon", "abandonn", 1), "").unwrap_err(),
            SeedError::UnknownWord(0),
        );
        // And a phrase of the wrong length, which no checksum can rescue.
        for wrong in ["abandon abandon about", ""] {
            assert_eq!(
                seed_from_phrase(wrong, "").unwrap_err(),
                SeedError::WordCount
            );
        }
        // The one that must still work.
        assert!(seed_from_phrase(ZEROS, "").is_ok());
    }

    /// A passphrase this module will not normalise is refused rather than
    /// stretched as its bytes happen to fall.
    ///
    /// BIP-39 says NFKD, and two spellings of the same accented passphrase are
    /// the same passphrase to a wallet that normalises and two different
    /// accounts to one that does not. Refusing is the honest half of not
    /// carrying a Unicode table.
    #[test]
    fn a_passphrase_this_cannot_normalise_is_refused() {
        assert_eq!(
            seed_from_phrase(ZEROS, "café").unwrap_err(),
            SeedError::Passphrase
        );
        assert!(seed_from_phrase(ZEROS, "cafe").is_ok());
        assert!(
            SeedError::Passphrase.message().contains("ASCII"),
            "the refusal says what would be accepted"
        );
    }

    /// Nothing that can be printed may carry the phrase or the seed.
    ///
    /// The rule `lighter_sign.rs` states for its key, applied to the one secret
    /// in this app that cannot be replaced: a leaked agent key trades badly for
    /// a while, a leaked recovery phrase is the account.
    #[test]
    fn no_printable_path_carries_the_phrase_or_the_seed() {
        let held = seed(ZEROS, "");
        assert_eq!(format!("{held:?}"), "Seed(<redacted>)");

        let mut printed = vec![format!("{held:?}")];
        for error in [
            SeedError::WordCount,
            SeedError::UnknownWord(3),
            SeedError::Checksum,
            SeedError::Passphrase,
            SeedError::Derivation,
        ] {
            printed.push(error.message());
            printed.push(format!("{error:?}"));
        }
        for text in printed {
            assert!(!text.contains("abandon"), "leaked a word: {text}");
            assert!(!text.contains("5eb00bbd"), "leaked the seed: {text}");
        }
    }

    fn hex_bytes(text: &str) -> Vec<u8> {
        (0..text.len() / 2)
            .map(|at| u8::from_str_radix(&text[at * 2..at * 2 + 2], 16).expect("hex"))
            .collect()
    }
}
