use super::*;

#[derive(Clone, Debug)]
pub enum ViewNode {
    Layout {
        kind: Layout,
        options: Box<LayoutOptions>,
        id: Option<Id>,
        styles: Vec<String>,
        children: Vec<ViewNode>,
        span: Span,
    },
    Container {
        options: Box<ContainerOptions>,
        id: Option<Id>,
        styles: Vec<String>,
        content: Box<ViewNode>,
        span: Span,
    },
    Overlay {
        id: Option<Id>,
        options: OverlayOptions,
        content: Box<ViewNode>,
        layer: Box<ViewNode>,
        span: Span,
    },
    PaneGrid {
        name: String,
        configuration: PaneConfiguration,
        options: PaneGridOptions,
        panes: Vec<PaneView>,
        templates: Vec<PaneTemplate>,
        span: Span,
    },
    Text {
        value: Expr,
        id: Option<Id>,
        options: TextOptions,
        styles: Vec<String>,
        span: Span,
    },
    RichText {
        id: Option<Id>,
        options: TextOptions,
        color: Option<String>,
        spans: Vec<RichSpan>,
        styles: Vec<String>,
        route: Option<Route>,
        span: Span,
    },
    Input {
        label: String,
        id: Option<Id>,
        binding: String,
        hint: String,
        disabled: Option<Expr>,
        options: InputOptions,
        styles: Vec<String>,
        span: Span,
    },
    Button {
        label: Option<String>,
        content: Option<Box<ViewNode>>,
        id: Option<Id>,
        disabled: Option<Expr>,
        options: ButtonOptions,
        styles: Vec<String>,
        route: Route,
        span: Span,
    },
    Checkbox {
        label: Expr,
        id: Option<Id>,
        checked: Expr,
        disabled: Option<Expr>,
        options: BoolControlOptions,
        style: Box<CheckboxStyleSet>,
        styles: Vec<String>,
        route: Route,
        span: Span,
    },
    Toggler {
        label: Expr,
        id: Option<Id>,
        checked: Expr,
        disabled: Option<Expr>,
        options: BoolControlOptions,
        style: Box<TogglerStyleSet>,
        styles: Vec<String>,
        route: Route,
        span: Span,
    },
    Slider {
        value: Expr,
        id: Option<Id>,
        min: Expr,
        max: Expr,
        step: Expr,
        options: Box<SliderOptions>,
        vertical: bool,
        styles: Vec<String>,
        route: Route,
        release: Option<Route>,
        span: Span,
    },
    Progress {
        value: Expr,
        id: Option<Id>,
        min: Expr,
        max: Expr,
        options: ProgressOptions,
        vertical: bool,
        styles: Vec<String>,
        span: Span,
    },
    Radio {
        label: Expr,
        id: Option<Id>,
        value: Expr,
        selected: Expr,
        options: BoolControlOptions,
        style: Box<RadioStyleSet>,
        styles: Vec<String>,
        route: Route,
        span: Span,
    },
    PickList {
        options: Expr,
        id: Option<Id>,
        selected: Expr,
        options_config: PickListOptions,
        route: Route,
        span: Span,
    },
    ComboBox {
        state: String,
        id: Option<Id>,
        selected: Expr,
        placeholder: String,
        options: ComboBoxOptions,
        route: Route,
        span: Span,
    },
    Rule {
        axis: Axis,
        id: Option<Id>,
        thickness: Expr,
        options: RuleOptions,
        styles: Vec<String>,
        span: Span,
    },
    QrCode {
        data: String,
        id: Option<Id>,
        cell_size: Option<Expr>,
        total_size: Option<Expr>,
        cell: Option<String>,
        background: Option<String>,
        span: Span,
    },
    Space {
        id: Option<Id>,
        width: Option<LengthValue>,
        height: Option<LengthValue>,
        styles: Vec<String>,
        span: Span,
    },
    If {
        condition: Expr,
        children: Vec<ViewNode>,
        span: Span,
    },
    For {
        item: String,
        items: Expr,
        children: Vec<ViewNode>,
        span: Span,
    },
    KeyedColumn {
        item: String,
        items: Expr,
        key: Expr,
        id: Option<Id>,
        options: Box<LayoutOptions>,
        child: Box<ViewNode>,
        span: Span,
    },
    Lazy {
        dependency: Expr,
        binding: String,
        id: Option<Id>,
        child: Box<ViewNode>,
        span: Span,
    },
    Markdown {
        content: String,
        id: Option<Id>,
        options: Box<MarkdownOptions>,
        route: Route,
        span: Span,
    },
    TextEditor {
        binding: String,
        id: Option<Id>,
        disabled: Option<Expr>,
        options: TextEditorOptions,
        span: Span,
    },
    Table {
        item: String,
        rows: Expr,
        id: Option<Id>,
        options: TableOptions,
        columns: Vec<TableColumn>,
        span: Span,
    },
    Component {
        name: String,
        args: Vec<ComponentArg>,
        id: Option<Id>,
        slots: Vec<ComponentSlot>,
        events: Vec<ComponentEventRoute>,
        route: Option<Route>,
        span: Span,
    },
    Slot {
        name: String,
        span: Span,
    },
    ExternComponent {
        function: String,
        id: Option<Id>,
        args: Vec<Expr>,
        route: Option<Route>,
        span: Span,
    },
    Themer {
        function: String,
        id: Option<Id>,
        args: Vec<Expr>,
        route: Option<Route>,
        span: Span,
    },
    Shader {
        function: String,
        id: Option<Id>,
        args: Vec<Expr>,
        width: Option<LengthValue>,
        height: Option<LengthValue>,
        route: Option<Route>,
        span: Span,
    },
    Media {
        kind: MediaKind,
        id: Option<Id>,
        source: Expr,
        options: MediaOptions,
        span: Span,
    },
    Tooltip {
        id: Option<Id>,
        options: TooltipOptions,
        content: Box<ViewNode>,
        tip: Box<ViewNode>,
        span: Span,
    },
    MouseArea {
        id: Option<Id>,
        options: MouseAreaOptions,
        content: Box<ViewNode>,
        span: Span,
    },
    ResizeHandle {
        id: Option<Id>,
        options: ResizeHandleOptions,
        content: Box<ViewNode>,
        span: Span,
    },
    Canvas {
        id: Option<Id>,
        options: Box<CanvasOptions>,
        locals: Vec<State>,
        commands: Vec<CanvasCommand>,
        events: Vec<CanvasEvent>,
        span: Span,
    },
    Theme {
        id: Option<Id>,
        preset: ThemePreset,
        text: Option<String>,
        background: Option<BackgroundValue>,
        content: Box<ViewNode>,
        span: Span,
    },
    Float {
        id: Option<Id>,
        scale: Expr,
        x: Expr,
        y: Expr,
        style: FloatStyleOptions,
        content: Box<ViewNode>,
        span: Span,
    },
    Pin {
        id: Option<Id>,
        width: Option<LengthValue>,
        height: Option<LengthValue>,
        x: Expr,
        y: Expr,
        content: Box<ViewNode>,
        span: Span,
    },
    Sensor {
        id: Option<Id>,
        options: SensorOptions,
        content: Box<ViewNode>,
        span: Span,
    },
    Responsive {
        id: Option<Id>,
        content: ResponsiveContent,
        width: Option<LengthValue>,
        height: Option<LengthValue>,
        span: Span,
    },
}
