[package]
name = "showcase"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
ducktape-ui = { path = "../../crates/ui", features = ["full"] }
iced = { version = "=0.14.0", features = ["smol"] }
ui-lang = { path = "../../crates/ui-lang" }
ui-lang-runtime = { path = "../../crates/ui-lang-runtime", version = "=0.1.0" }

[lints]
workspace = true
