[package]
name = "ice-downstream-consumer"
version = "0.0.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
ui-lang-components = { version = "=0.1.0", features = ["virtual-list"] }
iced = { version = "=0.14.0", default-features = false, features = ["tiny-skia", "wgpu", "x11"] }
ui-lang = "=0.1.0"
ui-lang-runtime = "=0.1.0"

[build-dependencies]
ui-lang-build = "=0.1.0"

[dev-dependencies]
ui-lang-runtime = { version = "=0.1.0", features = ["test-runtime"] }
