[package]
name = "music-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
iced = { version = "=0.14.0", default-features = false, features = ["image", "svg", "tokio", "wgpu", "x11"] }
ui-lang.workspace = true
ui-lang-runtime.workspace = true

[build-dependencies]
ui-lang-build.workspace = true

[dev-dependencies]
iced_runtime = "0.14.0"

[lints]
workspace = true
