[package]
name = "markdown-editor-example"
version = "0.1.0"
edition.workspace = true
publish = false

[dependencies]
iced = { version = "=0.14.0", default-features = false, features = ["advanced", "tiny-skia", "wgpu", "x11"] }
iced_highlighter = "=0.14.0"
pulldown-cmark = { version = "=0.12.2", default-features = false }
rfd = "=0.15.4"
ui-lang = { path = "../../crates/ui-lang" }
ui-lang-runtime = { path = "../../crates/ui-lang-runtime", version = "=0.1.0" }

[build-dependencies]
ui-lang-build = { path = "../../crates/ui-lang-build", version = "=0.1.0" }

[lints]
workspace = true
