[package]
name = "two-windows-example"
version = "0.1.0"
edition = "2024"
rust-version = "1.88"
publish = false

[dependencies]
iced = { version = "=0.14.0", features = ["smol"] }
ui-lang.workspace = true
ui-lang-runtime.workspace = true

[build-dependencies]
ui-lang-build.workspace = true

[lints.rust]
unsafe_code = "forbid"

[dev-dependencies]
ui-lang-runtime = { workspace = true, features = ["test-runtime"] }
