[package]
name = "browser-example"
version = "0.1.0"
edition.workspace = true
publish = false

[features]
default = []
cef = ["dep:cef", "dep:dispatch2"]

[dependencies]
cef = { version = "=151.8.0", default-features = false, features = ["build-util"], optional = true }
iced = { version = "=0.14.0", default-features = false, features = ["tiny-skia", "tokio", "wgpu", "x11"] }
ui-lang.workspace = true
ui-lang-runtime.workspace = true

[build-dependencies]
ui-lang-build.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
dispatch2 = { version = "0.3.1", optional = true }
plist = "1"
semver = "1"

[[bin]]
name = "browser-example"
path = "src/main.rs"

[[bin]]
name = "cef-browser-helper"
path = "src/bin/helper.rs"
required-features = ["cef"]

[[bin]]
name = "bundle-cef-browser"
path = "src/bin/bundle.rs"
required-features = ["cef"]

[package.metadata.cef.bundle]
helper_name = "cef-browser-helper"

[lints]
workspace = true

[dev-dependencies]
ui-lang-runtime = { workspace = true, features = ["test-runtime"] }
